learning_users/basic_app/urls.py
from django.urls import path
from . import views

app_name = 'basic_app'
urlpatterns = [
    path('register/', views.register, name = 'register'),
    path("login/", views.user_login, name="user_login"),
]

learning_users/learning_users/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path('basic_app/', include('basic_app.urls')),
    path("logout/", views.user_logout, name="user_logout"),
    path("profile/", views.profile, name="profile"),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional data
    portofolio_site = models.URLField(blank=True, null=True, max_length=200)
    
    profile_pic =models.ImageField(upload_to='profile_pics', blank=True, null=True)

    def __str__(self):
        return self.user.username

    def __unicode__(self):
        return 

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password', )

class UserProfileInfoForm(forms.ModelForm):
    
    class Meta:
        model = UserProfileInfo
        fields = ('portofolio_site', 'profile_pic', )

learning_users/basic_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import UserProfileInfo

# Create your views here.

def index(request):

    return render(request, 'basic_app/index.html')

@login_required(login_url='basic_app:user_login')
def profile(request):
    user_profile_data = get_object_or_404(UserProfileInfo, user = request.user)
    context = {
        'portofolio':user_profile_data.portofolio_site,
        'profile_picture':user_profile_data.profile_pic,
    }
    return render(request, 'basic_app/profile.html', context=context)

@login_required
def user_logout(request):
    logout(request)
    return redirect('index')

def register(request):
    
    if request.method == 'POST':
        
        user_form = UserForm(request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            user_name = user_form.cleaned_data.get('username')
            messages.success(request, 'Account was created for '+user_name)
            
            return redirect('basic_app:user_login')
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    context_data = {
        'user_form' : user_form,
        'profile_form' : profile_form,
    }

    return render(request, 'basic_app/registration.html', context = context_data)

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('index')
            else:
                return HttpResponse('ACOUNT IS NOT ACTIVE')
        else:
            messages.info(request, 'Username OR Password is incorrect!')

    context = {}
    return render(request, 'basic_app/login.html',context)





learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <title>{% block title %}{% endblock title %}</title>
    <style>
        .navbar-inverse .navbar-nav>li>a.hello-msg {
            color: #ffffff;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                </button> <a class="navbar-brand" href="{% url 'index' %}">Django</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    {% if user.is_authenticated and not user.is_superuser%}
                        <li>
                            <a href="{% url 'profile' %}" >Profile</a>
                        </li>
                    {% endif %}

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li>
                            <!-- <a class="hello-msg" href="#">Hello, {{ request.user }}<a> -->
                            <a class="hello-msg">Hello, {{ request.user }}</a>
                        </li>
                        <li>
                            <div class="btn-nav">
                                <a class="btn btn-primary btn-small navbar-btn" href="{% url 'user_logout' %}">Logout</a>
                            </div>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'basic_app:user_login' %}">Login</a>
                        </li>
                        <li>
                            <div class="btn-nav">
                                <a class="btn btn-primary btn-small navbar-btn" href="{% url 'basic_app:register' %}">Sign up!</a>
                            </div>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container page-header">
        {% block content_block %}
        {% endblock content_block %}
    </div>

</body>
</html>

learning_users/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}

{% block title %}
    Home
{% endblock title %}

{% block content_block %}

<div class="jumbotron">
    <div class="container">
        <h1>Welcome {% if user.is_authenticated %} {{request.user}} {% endif %} to my simple django template!</h1>
    </div>
</div>

{% endblock content_block %}

learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}

{% block title %}
    Login
{% endblock title %}

{% block content_block %}

    <div class="jumbotron">
        <div class="container">
            <form action="{% url 'basic_app:user_login' %}" method="post">
                {% csrf_token%}
                <label for="username">Username</label>
                <input type="text" name="username" placeholder="Enter Username">
        
                <label for="password">Password</label>
                <input type="password" name="password">
        
                <input type="submit" value="Login" class="btn btn-primary">
                
            </form>
            {% for message in messages %}
                <div class="alert alert-info" role="alert">                
                    <p id="messages"> {{ message }} </p>
                </div>
            {% endfor %} 
        </div>
    </div>
{% endblock content_block %}

learning_users/templates/basic_app/profile.html
{% extends 'basic_app/base.html' %}

{% block title %}
    profile
{% endblock title %}

{% block content_block %}
    
    <!-- <style>
        .data-type{
            color: cornflowerblue;
        }
        /* .profile_img{
            width: 100px;
            float: right;
            position: relative;
        } */
    </style>
    <div class="jumbotron">
        <div class="container">
            <div>
                <h1>Personal Data</h1>
            </div>
            <div>
                <h2><span class="data-type">User Name:</span> {{request.user}}</h2>
            </div>
            <div>
                <h2><span class="data-type">Email:</span> {{request.user.email}}</h2>
            </div>
            <div>
                <h2><span class="data-type">Portofoli site:</span> {{portofolio}}</h2>
            </div>
            <div class="img_container">
                <h2><span class="data-type">Profile Picture:</span></h2>
                <img src="{{profile_picture.url}}" class="img-thumbnail rounded float-right" alt="...">
            </div>
        </div>
    </div>
     -->

<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    
<style>
    body{padding-top:30px;}

    .glyphicon {  margin-bottom: 10px;margin-right: 10px;}

    small {
    display: block;
    line-height: 1.428571429;
    color: #999;
}
</style>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="well well-sm">
                <div class="row">
                    <div class="col-sm-6 col-md-4">
                        <img src="{{profile_picture.url}}" alt="" class="img-rounded img-responsive" />
                    </div>
                    <div class="col-sm-6 col-md-8">
                        <h4>{{request.user}}</h4>
                        <small><cite title="San Francisco, USA">San Francisco, USA <i class="glyphicon glyphicon-map-marker">
                        </i></cite></small>
                        <p>
                            <i class="glyphicon glyphicon-envelope"></i>{{request.user.email}}
                            <br />
                            <i class="glyphicon glyphicon-globe"></i><a href="{{portofolio}}">{{portofolio}}</a>
                            <br />
                            <i class="glyphicon glyphicon-gift"></i>Feb 08, 1999</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
     

{% endblock content_block %}


learning_users/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load static %}

{% block title %}
    Registration Page
{% endblock title %}

{% block content_block %}
    <div class="jumbotron">
        <div class="container">
            <h1> Register here! </h1>
            <h3>Fill out the form:</h3>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" value="Register" class="btn btn-primary btn-lg">
            </form>
        </div>
    </div>
{% endblock content_block %}